### ISSUE TITLE
COM extensibility APIs

### ISSUE THREAD

**Issue by sancarn** [sancarn/InfoLite-Lab#2]
# COM extensibility API

## Description

This issue will track this progress towards this feature

## Implementation progress

* [ ] Registered CLSID
* [ ] Registered ProgID (ideally)
* [ ] Full access to dynamic CGUI modification.

## Testing progress

* [ ] Develop VBScript test implementation. A msgbox "helloWorld" will suffice as far as implementations goes.
