### ISSUE TITLE
Settings 

### ISSUE THREAD

**Issue by sancarn** [sancarn/InfoLite-Lab#4]
# Settings

## Description

This issue will track this progress towards this feature

## Implementation progress

* [ ] Can be stored in any root
* [ ] Stores the location of other roots   `roots=["%A_AppDir%","%A_Documents%\InfoLab","%A_Appdata%\InfoLab"]`  
* [ ] Stored as JSON file?
* [ ] Also allow for other generic sections e.g. Keyboard Shortcuts and plugins
