### ISSUE TITLE
SQL Plugin

### ISSUE THREAD

**Issue by sancarn** [sancarn/InfoLite-Lab#6]
# SQL Plugin

## Description

This issue will track progress towards this feature

## Implementation progress

* [ ] Identification of SQL files via `.SQL` extension
* [ ] Basic execution of SQL scripts
* [ ] Context menu -> Edit to open an SQL Editor (Maybe using Ace? With intellisense?)
