### ISSUE TITLE
Toolbar Plugin

### ISSUE THREAD

**Issue by sancarn** [sancarn/InfoLite-Lab#7]
# Toolbar Plugin

## Description

This issue will track progress towards this feature

## Implementation progress

* [ ] Design TB file format
* [ ] Make TB files appear in the tree
* [ ] Pre-initialise IAccessibles to toolbar menus and child items for optimisation purposes. (There should only be 1 list of these)
* [ ] Execute toolbar buttons via IAccessible info path e.g. `File\Open Transportable Database`
* [ ] Ensure IAccessible existence is checked and it is ensured it belongs to the front window. 

## TB file format should include

* [ ] Ability to set a path for each different version of InfoWorks/Infonet.
* [ ] Ability to add null values for versions which do not support a particular feature.

e.g.

```js
{
  "type":"toolbar",
  "versions": {
    "IN-6.5":"File\\Open Transportable Database",
    "ICM-6.5":null,
    "IN-20.5":"File\\Open TDB" //for example only
  }
}
```
