### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by sancarn** [sancarn/InfoLite-Lab#8]
# Keyboard Shortcuts

## Description

This issue will track progress towards this feature

## Implementation progress

* [ ] Pre-requisites: Settings storage
* [ ] Ability to add local shortcuts
* [ ] Ability to add global shortcuts
* [ ] Shortcuts need to be stored in settings.
* [ ] Some indication of shortcuts in tree view would be nice!
